pipeline {
    agent any
    environment {
        MAVEN_HOME = "${WORKSPACE}/apache-maven-3.9.9"
        PATH = "${WORKSPACE}/apache-maven-3.9.9/bin:$PATH"
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Install Maven 3.9.9") {
            steps {
                sh '''
                  echo "Downloading Maven 3.9.9..."
                  curl -sSL https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz \
                  | tar -xz -C $WORKSPACE
                  echo "Maven installed at $WORKSPACE/apache-maven-3.9.9"
                '''
                sh "$WORKSPACE/apache-maven-3.9.9/bin/mvn -v"
            }
        }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
